# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b4b184854e6e2c93ce688f7396a387b8d568d60f2cd2ae293ecdbba245e0a16ff57ae9457db9f00dcbad4f3f3638aeff859fc6d5a61cea63233d94149cb185

test:
  secret_key_base: 54225a8e355e882dec781caace1fa1407359a9d5378d4dfb263a7bfc3a488184ad2c2b74e4de39638066aa660b9515314c9ca92a0c36f165f7424be309e2a448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
