# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22e7cbbe8a7193a531d4ee0f747d0fe1862a1afb86aa73160073a75877e2629bd20023500e7bd657b110659499353b2223d4236705a214e01fabcc9f41c4e23

test:
  secret_key_base: 41ef2afd6008ae19e520c72b418f03e90eca544a873cd0c7adc50d9ef1cf40d9ff2417396a046da268b973bc60df56920cafb38e77a4dc402ae513a3be0dfda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
