# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc3c56255fce77d02c290afa5df58927085ddbad6969322e01dc88d9684e2a496dd1644612e3899f9bf27dcefccaaeb14e8d6b9cdfb5b3996adafd59eb24ad2

test:
  secret_key_base: ad1b63fea534d3f00c46bd5f80b0474309922b23b1e453a50e042c0839f074fa4ef277cb524f5416fe4b4128cb092c21c71ce863d71e25fd2f7a14ad01efbb68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
